### ISSUE TITLE
Deleting String & Bad Image errors

### ISSUE THREAD

**Issue by misspent** [nptr/msstyleEditor#126] opened 2023-06-29 18:40 UTC
**Windows OS**: Windows 10 Pro 22H2 x64
**Windows Version**: 10.0.19045 Build 19045

**Expected behavior**
To work as intended

**Actual behavior**:

__Error 1__  
I keep getting error code `Deleting string resource with ID '33' failed with error '87'!` when attempting to Test  

![Test Error](https://i.imgur.com/gk06kjB.png)  

__Error 2__  
I also get error code `Bad image: Visual styles don't support PNGs with a color palette.` when attempting to replace an image  

![Image Error](https://i.imgur.com/XHYPArM.png)  

**Additional context**  
**Files from**: [ADT Theme by Niivu](https://github.com/niivu/Windows-10-themes/tree/main/ADT).  
I've tried searching this repository and doing a casual *Google* search about the issues I'm having, but to no avail. I'm going to assume it's something to do with my Windows or this tool. Furthermore, I'm new to editing Windows, but I'm willing to attempt basically anything you throw at me other than reinstalling. I've tried editing other themes too, and I'm still getting the issue. If you need more information, please let me know. I'd love to try making my own theme, so I'm all ears.

Thanks for making this; I hope we can figure it out. If we can't figure it out, then the more information the better, right?

**Checklist**
- [Yes] My uxtheme.dll is patched (used UltraUXThemePatcher)
- [Yes] I am using the latest version of msstyleEditor
- [Yes] None of the other issues cover this | I found one for Error 1, but not 2. I might be a wee bit blind, though.

**Comment by nptr** [comment] 2023-06-30 14:46
Hi,

**Error 1:**
I can reproduce the issue on my PC, but don't know how to fix it yet. To not hinder your project I implemented a workaround you can use in the meanwhile: [msstyleEditor_issue126.zip](https://github.com/nptr/msstyleEditor/files/11917410/msstyleEditor_issue126.zip)

_Note for myself:
Trying to delete an empty (?) string bucket (e.g.: 33) with `lang != 0` seems to fail if the bucket exists for `lang == 0`?
As a workaround I don't touch the string table at all. I don't need to update it for now anyways._

**Error 2:**
You are probably trying to replace an image with an 8-bit PNG. Those use a color palette instead of full 32-bit RGBA. Windows needs 32bit RGBA or something along this line. Save your PNG again with your favorite image editor and select another format.

**Comment by nptr** [comment] 2023-06-30 14:47
_Another note for myself: The visual style in question has a seemingly invalid (enum) property, where `nameId == 0xFFFFFFFF`. Part: Chevron, State: Common. msstyleEditor discards it gracefully. There is no connection to the errors mentioned above._

**Comment by JonesysMomma** [comment] 2023-07-15 22:22
Just so you know, I had both of these issues, if I use resource hacker to switch out the images, then reimport to msstyleditor, it works fine. The actual image file seems to be fine. I'm using Windows 11.

**Comment by ivelieu** [comment] 2024-03-20 09:20
I also happened to try customizing one of Niivu's themes I found, and I got the same first issue. I tried the msstyleEditor_issue126.zip version, which did save the skin after I loaded it and made no changes, and windows was able to load the theme, but it was clearly corrupted as it displayed some elements (taskbar, titlebar, etc.) as blue:
![image](https://github.com/nptr/msstyleEditor/assets/28797826/a354cd8e-82d4-4890-b950-33615866c9e1)
I can only speculate, but based on niivu's post [here](https://www.deviantart.com/niivu/art/Installing-Windows-Themes-UPDATED-708835586), and that most of the people at virtualcustoms.net (at which niivu was a regular poster) they seem to use vista style builder/windows style builder. So I would think it is an interoperability issue with how WSB saves the skins, but that is again just speculation. Although the [WSB forums](https://www.vistastylebuilder.com/forum/index.php) seem kind of dead.

 The exact skin in question I had this happen for is [here](https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521). 

This seems like a typical Libre software situation: one person hits a gold mine charging a fortune for what should in every right be free software, then it breaks and because it's closed source and the developer is gone, it takes a miracle ([such as this](https://virtualcustoms.net/showthread.php/70828-Custom-Class-Maps-and-Import-Scripts-for-Windows-10-TH2-RS1)) to keep using it, to the financial benefit of the gold miner. Desktop customization, especially in Windows is quite the rarity now so I can understand this happening, and which gives me all the more optimism for this project.

**Comment by nptr** [comment] 2024-06-28 14:57
[Version 2.1.0.0](https://github.com/nptr/msstyleEditor/releases/tag/2.1.0.0) includes the missing fix to the problem you described under "Error 1" in the bug report, so am closing this issue now. Feel free to reopen it in case something still doesn't quite work.

**Closed by nptr** 2024-06-28 14:57 UTC
Labels: bug
