### ISSUE TITLE
Ribbon menu skin changer

### ISSUE THREAD

**Issue by gdl-blue** [nptr/msstyleEditor#93] opened 2022-08-15 02:03 UTC
I don't like the Office 2013 style, so in settings is it possible to add ability to change the ribbon style to Office 2010/2007?

**Comment by nptr** [comment] 2022-08-23 16:43
I am using [this ribbon control](https://github.com/RibbonWinForms/RibbonWinForms) and it kind of supports 2007 and 2010 style. There is just no option to change it in msstyleEditor. Probably won't add one because the ribbon control is a bit buggy and the styles dont work and look like they are supposed to anymore.

**Comment by gdl-blue** [comment] 2022-08-26 23:27
Office 2010 looks nice, I see this program is MIT so can I modify code to have 2010 style (only for personal use)? 

and also, the show controls button is cut off, it can be fixed by changing line 111 in MainWindow.cs to `this.ribbonMenu.Size = new System.Drawing.Size(884, 121);`

**Comment by nptr** [comment] 2022-08-27 18:27
Yes, absolutely, go ahead! If you have any changes where you think others would also profit from feel free to open a pull request or send me a patch :)

Let me know if any code is unclear and I shall explain.

**Comment by gdl-blue** [comment] 2022-08-27 23:39
I like the Visual Studio 2008 skin the best but the DockPanel control doesn't have it yet I think.

changing line 111 in MainWindow.cs to `this.ribbonMenu.Size = new System.Drawing.Size(884, 121);` fixed the Show Controls button

![image](https://user-images.githubusercontent.com/55873929/187051590-0ba495e6-804a-4bbc-9800-66f8de161277.png)

**Comment by nptr** [comment] 2022-09-01 15:48
I can't reproduce the cut off text on multi line ribbon buttons but slightly increased the ribbon height anyways. But only 2px instead of 4px. Since you also managed to build and modify msstyleEditor to you liking i am closing this issue now.

**Closed by nptr** 2022-09-01 15:48 UTC
Labels: enhancement
